Feature/banner grid
deco-sites/boilerplaten1 pull request #2
Opened 2023-07-01 05:18 UTC by weslybrandao

## What is this contribution about?

## How to test it?

## Extra info

2023-07-01 16:37 UTC, gustavo-vasconcellos requested changes

2023-07-01 16:37 UTC, gustavo-vasconcellos commented on components/ui/BannerGrid.tsx
> +                          <svg
Para adicionar SVGs o correto é colocar no arquivo sprites.svg e usar o componente `Icon`.
Alem disso, coloca esse texto do botao para configurar pelo admin.
No daisy temos componentes para botao e outros, consulta os componentes antes de sair estilizando para poder poupar tempo de estilizaçao: https://daisyui.com/components/button/

2023-07-01 16:37 UTC, gustavo-vasconcellos commented on tailwind.config.ts
> +        "white": "#fff",
Todas essas cores ja existem
light green é a cor semantica `secondary`
default blue é a cor semantica `primary`
dark blue é a cor semantica `primary-focus` ou `focus-primary` nao lembro
white ja existe com o mesmo nome.

2023-07-01 16:37 UTC, gustavo-vasconcellos commented on components/ui/BannerGrid.tsx
> +                class={`invisible transition duration-700 group-hover:visible w-full z-999 top-0 opacity-0 group-hover:opacity-60 h-full bg-default-blue absolute ${
Acho que seria mais facil se voce botasse todos os elementos que devem aparecer dentro do foreground, assim nao precisa ficar colocando o `group-hover` em tudo que voce precisa que apareça mas sim so nesse elemento. Fica mais facil de dar manutençao se tem menos lugares para editar.

2023-07-02 01:42 UTC, weslybrandao commented on components/ui/BannerGrid.tsx
> +                class={`invisible transition duration-700 group-hover:visible w-full z-999 top-0 opacity-0 group-hover:opacity-60 h-full bg-default-blue absolute ${
No caso desse cara é só o botão e esse botão vai ter um hover individual, então não sei se faz sentido

2023-07-02 01:42 UTC, weslybrandao commented on tailwind.config.ts
> +        "white": "#fff",
Resolved

2023-07-02 01:42 UTC, weslybrandao commented on components/ui/BannerGrid.tsx
> +                          <svg
Resolved

2023-07-03 01:33 UTC, merged