Banner initial commit
deco-sites/boilerplaten1 pull request #6
Opened 2023-07-03 05:09 UTC by weslybrandao

## What is this contribution about?

## How to test it?

## Extra info

2023-07-04 15:46 UTC, gustavo-vasconcellos requested changes

2023-07-06 04:36 UTC, weslybrandao commented on components/search/SearchResult.tsx
>              itemListElement={breadcrumb?.itemListElement}
Resolvido!

2023-07-06 14:51 UTC, gustavo-vasconcellos requested changes

2023-07-06 14:51 UTC, gustavo-vasconcellos commented on components/ui/BannerPLP.tsx
> +          height={80}
A imagem no mobile ta com a qualidade baixa porque esses valores sao pequenos demais. Como o mobile entra em 990px nem usando a imagem com a largura de 560px que o Source gera fica boa. Coloca uma largura de 480 e  a altura proporcional ao layout que deve resolver

2023-07-06 14:51 UTC, gustavo-vasconcellos commented on components/ui/BannerPLP.tsx
> +        />
Ou voce usa Image ou Picture, os dois nao pode pq é "ambiguo". Depois olha a implementaçåo de cada um e vai notar que eles fazem algumas coisas parecidas, a força no Picture é renderizar desktop e mobile.

2023-07-06 14:51 UTC, gustavo-vasconcellos commented on components/ui/BreadcrumbCategory.tsx
> +  page: LoaderReturnType<ProductListingPage | null>;
Peço para que reveja o video que te enviei, nele explica que fazendo dessa forma voce esta pegando todos os valores do ProductListingPage e enviado para o BreadcrumbCategory e isso nao é necessario pois voce so precisa da propriedade `breadcrumb`

2023-07-06 14:51 UTC, gustavo-vasconcellos commented on components/ui/BreadcrumbCategory.tsx
> +}
componente desnecessario, pode colocar essa div diretamente no `BreadcrumbCategory`

2023-07-06 14:51 UTC, gustavo-vasconcellos commented on components/ui/BreadcrumbCategory.tsx
> +  if (!page || !page.breadcrumb) {
```suggestion
  if (!page?.breadcrumb) {
```

2023-07-06 14:51 UTC, gustavo-vasconcellos commented on components/ui/BreadcrumbCategory.tsx
> +    <div class="container">
Esse container é desnecessário pois para colocar a section do breacrumb na pagina voce precisa usar a section Container que ja configura isso para voce.

2023-07-09 00:52 UTC, closed without merging